export * from './Header/Header';
export * from './Devices/Devices';
export * from './Home/Home';
export * from './Order/Order';
export * from './Login/Login';
export * from './Register/Register';
export * from './Account/Account';
export * from './Admin/Admin';
export * from './DeviceDetails/DeviceDetails';